version: "3.3"
services:



  content_database:
    container_name: content_database
    image: mongo:latest
    volumes:
    - ./mongodb/data/db:/data/db
    ports:
    - "27017:27017"
    environment:
      - MONGODB_DATABASE=content_database

  user_database:
    container_name: user_database
    image: postgres:10.5
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=user_database
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
