spring:
  data:
    mongodb:
      host: content_database
      port: 27017
      database: content_database

  datasource:
    jdbc-url: jdbc:postgresql://user_database:5432/user_database
    username: postgres
    password: postgres

  application:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000
